name: Verify Docker Build

on:
  pull_request:

concurrency:
  group: golang-docker-build-rink-be
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/teammadduck
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Verify Docker build
        run: |
          if [ $? -eq 0 ]; then
            echo "Docker build succeeded"
            exit 0
          else
            echo "Docker build failed"
            exit 1
          fi
